skip_tags: true

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node
  # install modules
  - npm install
  
# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run build
build: off
artifacts:
  - path: dist
    name: auto_pac
    type: zip
    
environment:
  access_token:
    secure: FRSCEjosDbpSEz4zOESBW+HsNXZ3XmmH4jEvgZ/AMZQlyCSXlpXKFObdPg6Y9aHi    

deploy:
  release: v$(APPVEYOR_BUILD_VERSION)
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: FRSCEjosDbpSEz4zOESBW+HsNXZ3XmmH4jEvgZ/AMZQlyCSXlpXKFObdPg6Y9aHi # your encrypted token from GitHub. appveyor Accoun设置中添加Encrypt YAML 隐藏真实key
  artifact: /.*\.zip/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
